/**
 * A green oracle is useful only if it rejects a plausible broken control.
 * The laws and sources are beside each receiving oracle; controls here remove one
 * production defense at a time without changing the expected result.
 * Model: each isolated baseline passes, then its mutant reaches the named semantic
 * assertion. Nonzero exit alone is insufficient: setup errors and timeouts fail
 * this verifier. The controls cover claims, at-rest secrets, logs, limiter
 * identity, browser framing, cross-isolate revocation and protected transport.
 * Driver: a disposable source copy runs the same Worker, browser or race test.
 * Refinement: exact mutation anchor, baseline exit, failure checkpoint and no runner
 * error. Restore each source file before the next control.
 * Limits: mutation detection is sensitivity evidence, not absence of all defects.
 * No control changes the working checkout or audits deployed services.
 */
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { tmpdir } from 'node:os';

const root = resolve('.'), temporary = mkdtempSync(join(tmpdir(), 'blygger-security-controls-'));
const controls = [
  { name: 'review grant listing trusts revoked rows', changes: [{ file: 'src/authorization-api.ts', from: 'AND NOT EXISTS (SELECT 1 FROM oauth_revocations WHERE grant_id=oauth_authorizations.grant_id)', to: '' }], kind: 'worker', test: 'test/auth-security.oracle.test.ts', pattern: 'stale persisted rows', checkpoint: 'stored stale grant rows cannot appear active' },
  { name: 'review private media accepts cleartext cookies', changes: [{ file: 'src/index.ts', from: "if (url.protocol !== 'https:' && !['localhost', '127.0.0.1', '[::1]'].includes(url.hostname))", to: 'if (false)' }], kind: 'worker', test: 'test/media-visibility-security.oracle.test.ts', pattern: 'live read authority', checkpoint: 'private bytes cannot be read over non-loopback cleartext transport' },

  { name: "review browser navigation trusts legacy protocol markup", changes: [{ file: "src/pages.ts", from: "fetch(mount + \"/\" + kind + \"/\" + id + \"/v\" + v + \"/\")\n        .then(function (r) { if (!r.ok) throw new Error(String(r.status)); return r.text(); })\n        .then(function (html) {\n          var page = new DOMParser().parseFromString(html, \"text/html\");\n          var body = page.querySelector(\"article .item-content\");\n          if (!body) throw new Error(\"Missing version presentation\");\n          var note = page.querySelector(\"article .version-note\");\n          var holder = page.querySelector(\"article[data-generated]\");\n          cache[v] = { html: body.innerHTML, note: note ? note.textContent : \"\", gen: holder ? holder.getAttribute(\"data-generated\") : null };", to: "fetch(mount + \"/items/\" + id + \"/v\" + v + \".json\")\n        .then(function (r) { if (!r.ok) throw new Error(String(r.status)); return r.json(); })\n        .then(function (data) {\n          cache[v] = { html: data.content_html || \"\", note: data.note ? \"\u201c\" + data.note + \"\u201d\" : \"\", gen: data.generated ? JSON.stringify(data.generated) : null };" }], kind: "browser", test: "e2e/imported-html-security.spec.ts", pattern: "public version navigation", checkpoint: "version navigation must not attempt owner-authority calls" },
  { name: 'review transclusion preview trusts imported HTML', changes: [{ file: 'src/transclusion.ts', from: 'html: await sanitizeHtml(result.html)', to: 'html: result.html' }], kind: 'worker', test: 'test/review-content-security.oracle.test.ts', pattern: 'transclusion preview', checkpoint: 'transclusion preview cannot execute imported HTML' },
  { name: 'review provenance attributes are unescaped', changes: [{ file: 'src/pages.ts', from: 'escapeHref(link.href)', to: 'link.href' }], kind: 'worker', test: 'test/review-content-security.oracle.test.ts', pattern: 'public transclusion provenance', checkpoint: 'provenance href cannot create attacker markup' },
  { name: "review stored citation links are unescaped", changes: [{ file: "src/pages.ts", from: "href=\"${escapeHref(url)}\"", to: "href=\"${escapeHtml(url)}\"" }], kind: "worker", test: "test/review-content-security.oracle.test.ts", pattern: "a stored", checkpoint: "stored citation cannot create an active link" },
  { name: "review citation write accepts active schemes", changes: [{ file: "src/stub.ts", from: "![\"http:\", \"https:\"].includes(new URL(url).protocol)", to: "false" }], kind: "worker", test: "test/review-content-security.oracle.test.ts", pattern: "with an active scheme is refused", checkpoint: "active-scheme citations are refused at write" },
  { name: "review author links accept active schemes", changes: [{ file: "src/api.ts", from: "&& isFollowableUrl(l.url))) return c.json({ error: \"author_links", to: ")) return c.json({ error: \"author_links" }], kind: "worker", test: "test/review-content-security.oracle.test.ts", pattern: "author links refuse", checkpoint: "active-scheme author links are refused at write" },
  { name: "review stored author links leave unfiltered", changes: [{ file: "src/model.ts", from: "&& isFollowableUrl(l.url));", to: ");" }], kind: "worker", test: "test/review-content-security.oracle.test.ts", pattern: "author links refuse", checkpoint: "the manifest does not publish an active-scheme author link" },
  { name: "review site_url write accepts any scheme", changes: [{ file: "src/api.ts", from: "if (patch.site_url && !(URL.canParse", to: "if (false && !(URL.canParse" }], kind: "worker", test: "test/review-content-security.oracle.test.ts", pattern: "manage-writable", checkpoint: "site_url accepts only an absolute http(s) URL" },
  { name: "review stored site_url is trusted", changes: [{ file: "src/protocol.ts", from: "if (settings.site_url && URL.canParse(settings.site_url) && [\"http:\", \"https:\"].includes(new URL(settings.site_url).protocol)) {", to: "if (settings.site_url) {" }], kind: "worker", test: "test/review-content-security.oracle.test.ts", pattern: "manage-writable", checkpoint: "a stored legacy site_url cannot activate markup" },
  { name: "review collection name is unescaped", changes: [{ file: "src/importer/pages.ts", from: "<h2>${escapeHtml(hopper.name)}</h2>", to: "<h2>${hopper.name}</h2>" }], kind: "worker", test: "test/review-content-security.oracle.test.ts", pattern: "no delegated item", checkpoint: "delegated text cannot activate markup" },
  { name: "review citation caption is unescaped", changes: [{ file: "src/pages.ts", from: "`<cite>${escapeHtml(cite.source)}</cite>`", to: "`<cite>${cite.source}</cite>`" }], kind: "worker", test: "test/review-content-security.oracle.test.ts", pattern: "no delegated item", checkpoint: "delegated text cannot activate markup" },
  { name: 'review abandoned registrations never expire', changes: [{ file: 'src/security-budgets.ts', from: 'DELETE FROM oauthClient WHERE userId IS NULL AND julianday(createdAt) <= julianday(?)', to: 'DELETE FROM oauthClient WHERE userId IS NULL AND createdAt <= ?' }, { file: 'src/security-budgets.ts', from: "86400) * 1000).toISOString();", to: '86400) * 1000).getTime();' }], kind: 'worker', test: 'test/registration-retention-security.oracle.test.ts', pattern: 'abandoned old', checkpoint: 'abandoned anonymous storage must become reclaimable' },
  { name: 'review delegated work spends owner capacity', changes: [{ file: 'src/security-budgets.ts', from: 'grant ? `${kind}:grant:${grant}` : `${kind}:owner`', to: '`${kind}:owner`' }], kind: 'worker', test: 'test/delegated-budget-security.oracle.test.ts', pattern: 'aggregate exhaustion', checkpoint: 'a delegated grant cannot spend reserved owner capacity' },
  { name: 'review AI owner reserve is absent', changes: [{ file: 'src/security-budgets.ts', from: 'const reserve = Math.min(total, securityLimit(env.AI_OWNER_RESERVED_CALLS, 5));', to: 'const reserve = 0;' }], kind: 'worker', test: 'test/delegated-budget-security.oracle.test.ts', pattern: 'delegated AI', checkpoint: 'promise resolved' },
  { name: "review MCP AI work loses its grant", changes: [{ file: "src/owner-api.ts", from: "c.env = withWorkPrincipal(c.env, delegated ?? undefined);", to: "c.env = withWorkPrincipal(c.env, undefined);" }], kind: "worker", test: "test/delegated-budget-security.oracle.test.ts", pattern: "through an MCP tool", checkpoint: "MCP AI work cannot reach the owner reserve" },
  { name: 'review unpublished media is public', changes: [{ file: 'src/index.ts', from: 'if (!publicUse) {', to: 'if (false) {' }], kind: 'worker', test: 'test/media-visibility-security.oracle.test.ts', pattern: 'unattached uploads', checkpoint: 'draft bytes are not anonymous publications' },
  { name: "review withdrawal retracts version media", changes: [{ file: "src/index.ts", from: "instr(content_html, ?) > 0)", to: "instr(content_html, ?) > 0 AND item_id IN (SELECT id FROM items WHERE status='public'))" }], kind: "worker", test: "test/media-visibility-security.oracle.test.ts", pattern: "withdrawal keeps published media", checkpoint: "a published media URL keeps serving after withdrawal" },
  { name: "review withdrawal retracts attachments", changes: [{ file: "src/index.ts", from: "WHERE id=? AND version>0 AND ?<>1", to: "WHERE id=? AND status='public' AND version>0 AND ?<>1" }], kind: "worker", test: "test/media-visibility-security.oracle.test.ts", pattern: "withdrawal keeps published media", checkpoint: "a published media URL keeps serving after withdrawal" },
  { name: "review highlight edit skips publish scope", changes: [{ file: "src/owner-api.ts", from: " || body.highlight !== undefined", to: "" }, { file: "src/mcp.ts", from: " || args?.body?.highlight !== undefined", to: "" }], kind: "worker", test: "test/rest-permissions.oracle.test.ts", pattern: "generated highlighting", checkpoint: "a public edit needs owner:draft and owner:publish" },
  { name: "review avatar choice skips publish scope", changes: [{ file: "src/owner-api.ts", from: "if (body.avatar_media_id !== undefined) required.push('owner:publish');", to: "" }, { file: "src/mcp.ts", from: "if (name === 'updateSettings' && args?.body?.avatar_media_id !== undefined) required.push('owner:publish');", to: "" }], kind: "worker", test: "test/media-visibility-security.oracle.test.ts", pattern: "choosing the avatar", checkpoint: "draft+manage cannot publish bytes as the avatar" },
  { name: 'review refresh introspection ignores revocation', changes: [{ file: 'src/oauth-routes.ts', from: 'if (!grant) return c.json({ active: false });', to: 'if (false) return c.json({ active: false });' }], kind: 'worker', test: 'test/auth-security.oracle.test.ts', pattern: 'reports a revoked refresh_token', checkpoint: 'a revoked grant introspects inactive' },
  { name: 'review consent hides native destination', changes: [{ file: 'src/oauth-routes.ts', from: "escapeHtml(params.get('redirect_uri')!)", to: "escapeHtml(new URL(params.get('redirect_uri')!).host)" }], kind: 'worker', test: 'test/consent-destination-security.oracle.test.ts', pattern: 'exact native destination', checkpoint: 'owner consent must identify scheme and callback path' },
  { name: 'review fork exception leaks dependency data', changes: [{ file: 'src/read-api.ts', from: 'error: `could not reach ${origin}`', to: 'error: `could not reach ${origin}: disposable-transport-secret-sentinel`' }], kind: 'worker', test: 'test/fork-fetch-security.oracle.test.ts', pattern: 'exception secrets', checkpoint: 'transport exception text is not API data' },
  { name: 'review late grant recording resurrects revocation', changes: [{ file: 'src/oauth.ts', from: 'WHERE NOT EXISTS (SELECT 1 FROM oauth_revocations WHERE grant_id=?) AND', to: 'WHERE (? IS NOT NULL) AND' }], kind: 'worker', test: 'test/auth-security.oracle.test.ts', pattern: 'a revoke between', checkpoint: 'revocation tombstone must block late grant persistence' },
  { name: 'review browser transclusion can mint lasting authority', changes: [{ file: 'src/pages.ts', from: 'await sanitizeHtml(latest?.content_html ?? "")', to: 'latest?.content_html ?? ""' }], kind: 'browser', test: 'e2e/imported-html-security.spec.ts', pattern: 'native import cannot mint owner authority through published thread', checkpoint: 'imported content must not attempt owner-authority calls' },
  { name: 'review browser provenance can mint lasting authority', changes: [{ file: 'src/importer/pages.ts', from: 'escapeHref(sourceLink)', to: 'sourceLink' }], kind: 'browser', test: 'e2e/imported-html-security.spec.ts', pattern: 'native import cannot mint owner authority through public collection', checkpoint: 'imported content must not attempt owner-authority calls' },

  { name: 'admission MCP discovery bypasses envelope budget', changes: [{ file: 'src/mcp.ts', from: "if (!await admitMcp(env, access))", to: 'if (false)' }], kind: 'worker', test: 'test/work-admission-security.oracle.test.ts', pattern: 'MCP discovery', checkpoint: 'MCP control work requires admission too' },
  { name: 'admission counter ignores its ceiling', changes: [{ file: 'src/security-budgets.ts', from: 'WHERE security_budgets.window <> excluded.window OR security_budgets.used < ? RETURNING used', to: 'WHERE ? > 0 RETURNING used' }], kind: 'worker', test: 'test/work-admission-security.oracle.test.ts', pattern: 'atomic admission', checkpoint: 'concurrent writes share one atomic budget' },
  { name: 'admission AI bypasses daily calls', changes: [{ file: 'src/ai/provider.ts', from: "if (!await admitAi(env))", to: 'if (false)' }], kind: 'worker', test: 'test/work-admission-security.oracle.test.ts', pattern: 'daily AI budget counts', checkpoint: 'promise resolved' },
  { name: 'admission anonymous storage ignores cap', changes: [{ file: 'src/security-budgets.ts', from: '(SELECT COUNT(*) FROM security_registrations WHERE expires > ?) < ? RETURNING id', to: '(SELECT COUNT(*) FROM security_registrations WHERE expires > ?) >= 0 AND ? > 0 RETURNING id' }], kind: 'worker', test: 'test/work-admission-security.oracle.test.ts', pattern: 'bounds anonymous registration storage', checkpoint: 'registration cannot exceed the stored-client cap' },
  { name: 'admission REST body ignores operator cap', changes: [{ file: 'src/owner-api.ts', from: 'securityLimit(c.env.API_BODY_LIMIT, 8 * 1024 * 1024)', to: '64 * 1024 * 1024' }], kind: 'worker', test: 'test/request-body-security.oracle.test.ts', pattern: 'REST refuses', checkpoint: 'byte admission must precede write work' },
  { name: 'admission outbound private destinations accepted', changes: [{ file: 'src/outbound-policy.ts', from: 'if (allowPrivate) return;', to: 'if (true) return;' }], kind: 'worker', test: 'test/outbound-destination-security.oracle.test.ts', pattern: 'restricted destination', checkpoint: 'promise resolved' },

  { name: 'stale native cookies authorize after password reset', changes: [{ file: 'src/oauth-routes.ts', from: "const headers = new Headers(c.req.raw.headers); headers.delete('cookie');", to: 'const headers = new Headers(c.req.raw.headers);' }], kind: 'worker', test: 'test/owner-reset.oracle.test.ts', pattern: 'stale native browser cookies', checkpoint: 'stale browser sessions cannot silently authorize after reset' },
  { name: 'remembered consent survives grant revoke', changes: [{ file: 'src/oauth.ts', from: 'DELETE FROM oauthConsent WHERE userId=? AND clientId IN', to: 'DELETE FROM oauthConsent WHERE 0 AND userId=? AND clientId IN' }], kind: 'worker', test: 'test/oauth-grant-list.oracle.test.ts', pattern: 'new owner consent', checkpoint: 'revocation cannot be bypassed by silent reauthorization' },
  { name: 'unclassified writes fall back to read', changes: [{ file: 'src/owner-api.ts', from: "if (!operation && !['GET', 'HEAD'].includes(c.req.method))", to: 'if (false)' }], kind: 'worker', test: 'test/review-auth-regressions.test.ts', pattern: 'undeclared write', checkpoint: 'unclassified writes must fail closed' },
  { name: 'draft operations accept read scope', changes: [{ file: 'src/permissions.ts', from: "if (draft.has(operation)) return ['owner:draft'];", to: "if (draft.has(operation)) return ['owner:read'];" }], kind: 'worker', test: 'test/rest-permissions.oracle.test.ts', pattern: 'every REST operation', checkpoint: 'createItem:' },
  { name: 'media publication commit guard removed', changes: [{ file: 'src/model.ts', from: 'WHERE ? = 0 OR ? IS NULL OR EXISTS', to: 'WHERE ? >= 0 OR ? IS NULL OR EXISTS' }], kind: 'worker', test: 'test/review-auth-regressions.test.ts', pattern: 'publication races', checkpoint: 'publication racing upload must deny draft-only attachment' },
  { name: 'MCP media publication gate removed', changes: [{ file: 'src/model.ts', from: 'WHERE ? = 0 OR ? IS NULL OR EXISTS', to: 'WHERE ? >= 0 OR ? IS NULL OR EXISTS' }], kind: 'worker', test: 'test/mcp-media.oracle.test.ts', pattern: 'published attachments', checkpoint: 'MCP drafting cannot publish an attachment' },

  { name: 'subject guard removed', changes: [{ file: 'src/oauth.ts', from: "validated.sub !== 'owner' || ", to: '' }], kind: 'worker', test: 'test/auth-security.oracle.test.ts', pattern: 'invalid subject claims', checkpoint: 'invalid claim must deny protected reads' },
  { name: 'raw credential storage', changes: [{ file: 'src/oauth.ts', from: "const oauth: OAuthOptions<string[]> = {", to: "const oauth: OAuthOptions<string[]> = { storeTokens: { hash: token => token }," }], kind: 'worker', test: 'test/auth-security.oracle.test.ts', pattern: 'does not store recoverable', checkpoint: 'stored auth rows must not contain these plaintext credentials' },
  { name: 'dependency error logged in full', changes: [{ file: 'src/oauth-routes.ts', from: "console.error('OAuth request failed', requestError(error, c));", to: "console.error('OAuth request failed', String(error));" }], kind: 'worker', test: 'test/auth-security.oracle.test.ts', pattern: 'does not leak sentinel', checkpoint: 'dependency logging must not leak credentials' },
  { name: 'unencrypted private signing key', changes: [{ file: 'src/oauth.ts', from: "jwt({ jwks: { keyPairConfig:", to: "jwt({ jwks: { disablePrivateKeyEncryption: true, keyPairConfig:" }], kind: 'worker', test: 'test/auth-security.oracle.test.ts', pattern: 'does not store recoverable', checkpoint: 'private signing key must be encrypted' },
  { name: 'introspection owner revocation omitted', changes: [{ file: 'src/oauth-routes.ts', from: 'if (value.active) {', to: 'if (false) {' }], kind: 'worker', test: 'test/auth-security.oracle.test.ts', pattern: 'reports a revoked access_token inactive', checkpoint: 'a revoked grant introspects inactive' },
  { name: 'spoofable limiter identity', changes: [{ file: 'src/oauth.ts', from: "ipAddressHeaders: ['cf-connecting-ip']", to: "ipAddressHeaders: ['x-forwarded-for']" }], kind: 'worker', test: 'test/auth-deployment.oracle.test.ts', pattern: 'shares an atomic registration budget', checkpoint: 'spoofed forwarded addresses share one edge budget' },
  { name: 'frame blocking removed', changes: [{ file: 'src/spa.ts', from: "c.header('Content-Security-Policy', \"frame-ancestors 'none'\");", to: '' }, { file: 'src/spa.ts', from: "c.header('X-Frame-Options', 'DENY');", to: '' }, { file: 'src/oauth-routes.ts', from: "'Content-Security-Policy': \"frame-ancestors 'none'\", 'X-Frame-Options': 'DENY', ", to: '' }], kind: 'browser', test: 'e2e/client-access.spec.ts', pattern: 'hostile ancestor', checkpoint: 'Expected value: "net::ERR_BLOCKED_BY_RESPONSE"' },
  { name: 'cross-isolate family tombstone omitted', changes: [{ file: 'src/oauth-routes.ts', from: "if (seen && seen.client === clientId", to: "if (false && seen.client === clientId" }], kind: 'race', test: 'scripts/verify-auth-security-race.ts', pattern: '', checkpoint: 'Cross-isolate replay must revoke the existing signed access token' },
  { name: 'root and contract errors logged in full', changes: [{ file: 'src/index.ts', from: "console.error('Worker request failed', requestError(_error, c));", to: 'console.error(_error);' }, { file: 'src/contract/app.ts', from: "console.error('API request failed', requestError(error, c));", to: 'console.error(error);' }], kind: 'worker', test: 'test/auth-security.oracle.test.ts', pattern: 'does not leak sentinel', checkpoint: 'dependency logging must not leak credentials' },
  { name: 'native raw fallback logging restored', changes: [{ file: 'src/oauth.ts', from: 'onAPIError: { throw: true }', to: 'onAPIError: { throw: false }' }], kind: 'worker', test: 'test/auth-security.oracle.test.ts', pattern: 'does not leak sentinel', checkpoint: 'dependency logging must not leak credentials' },
  { name: 'cleartext transport guard removed', changes: [{ file: 'src/index.ts', from: "if (url.protocol !== 'https:' && !loopback)", to: 'if (false)' }], kind: 'worker', test: 'test/auth-security.oracle.test.ts', pattern: 'cleartext auth transport', checkpoint: 'cleartext protected transport must fail closed' },
  { name: 'uploaded media sandbox removed', changes: [{ file: 'src/index.ts', from: '"Content-Security-Policy": "sandbox; script-src \'none\'",', to: '' }], kind: 'browser', test: 'e2e/client-access.spec.ts', pattern: 'SVG uploads', checkpoint: 'data-script-ran="yes"' },
  { name: 'Basic replay client classification omitted', changes: [{ file: 'src/oauth-routes.ts', from: 'if (basic) {', to: 'if (false) {' }], kind: 'worker', test: 'test/auth-security.oracle.test.ts', pattern: 'authenticated Basic refresh replay', checkpoint: 'authenticated Basic replay revokes the compromised JWT grant' },
];
// Browser controls share Playwright's server port; worker/race controls can run
// while a separate browser verification owns it. The default still runs all controls.
const selector = process.argv[2];
const selected = selector === '--existing-worker' ? controls.filter(control => control.kind !== 'browser' && !control.name.startsWith('admission ')) : selector === '--browser' ? controls.filter(control => control.kind === 'browser') : selector === '--exclude-browser' ? controls.filter(control => control.kind !== 'browser') : selector ? controls.filter(control => control.name.includes(selector)) : controls;
assert.ok(selected.length, 'No mutation matches the requested name');
try {
  const tracked = execFileSync('git', ['ls-files', '-z'], { encoding: 'utf8' }).split('\0').filter(Boolean);
  const source = execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard', '-z', '--', 'src', 'test', 'e2e', 'scripts', 'migrations', 'docs'], { encoding: 'utf8' }).split('\0').filter(Boolean);
  for (const file of new Set([...tracked, ...source])) { const destination = join(temporary, file); mkdirSync(dirname(destination), { recursive: true }); cpSync(join(root, file), destination); }
  cpSync(join(root, 'sdk/dist'), join(temporary, 'sdk/dist'), { recursive: true });
  cpSync(join(root, 'build'), join(temporary, 'build'), { recursive: true });
  symlinkSync(join(root, 'node_modules'), join(temporary, 'node_modules'), 'dir');
  const execute = (control: typeof controls[number]) => spawnSync(process.execPath, control.kind === 'race' ? ['--import', 'tsx', control.test] : control.kind === 'browser' ? [join(root, 'node_modules/@playwright/test/cli.js'), 'test', control.test, '--project=desktop', '-g', control.pattern] : [join(root, 'node_modules/vitest/vitest.mjs'), 'run', '--maxWorkers=1', control.test, '-t', control.pattern], { cwd: temporary, encoding: 'utf8', timeout: 90000, env: { ...process.env, WRANGLER_LOG_PATH: join(temporary, 'wrangler.log'), NO_COLOR: '1' } });
  for (const control of selected) {
    const baseline = execute(control);
    assert.equal(baseline.error, undefined); assert.equal(baseline.signal, null); assert.equal(baseline.status, 0, 'Baseline failed: ' + control.name + '\n' + baseline.stdout + baseline.stderr);
    // A pattern that selects nothing exits 0 too; the mutant would then
    // "survive" or pass a checkpoint without any test having run.
    if (control.kind !== 'race') assert.ok(/\b[1-9]\d* passed\b/.test(baseline.stdout + baseline.stderr), 'Baseline ran no tests: ' + control.name);
    const originals = new Map<string, string>();
    try {
      for (const change of control.changes) {
        const file = join(temporary, change.file), original = readFileSync(file, 'utf8');
        if (!originals.has(file)) originals.set(file, original);
        assert.ok(original.includes(change.from), 'Missing exact mutation anchor: ' + control.name);
        writeFileSync(file, original.replaceAll(change.from, change.to));
      }
      const result = execute(control), output = result.stdout + '\n' + result.stderr;
      writeFileSync(join(root, 'build', 'security-mutant-' + controls.indexOf(control) + '.log'), output);
      assert.equal(result.error, undefined, 'Runner error: ' + control.name);
      assert.equal(result.signal, null, 'Timeout: ' + control.name);
      assert.notEqual(result.status, 0, 'Survived: ' + control.name);
      assert.ok(!/Test timeout|Failed to load|Cannot find module|webServer was not able/.test(output), 'Setup or timeout is not security RED: ' + control.name);
      assert.ok(output.includes(control.checkpoint), 'Missing semantic checkpoint: ' + control.name);
      console.log('Caught: ' + control.name);
    } finally { for (const [file, original] of originals) writeFileSync(file, original); }
  }
} finally { rmSync(temporary, { recursive: true, force: true }); }
