//! Markdown-engine parity beyond the hand-written corpus, against output of
//! the Worker's own `renderMarkdown` (markdown-it 14, `html: false`, linkify,
//! embeds plugin), generated by `fixtures/gen_parity.mjs`:
//! - the 652 CommonMark 0.31.2 spec examples;
//! - linkify-it's and markdown-it's own linkify test vectors.

mod common;

use common::{fixtures_dir, normalize};
use serde_json::Value;

/// Cases known to differ, by suite and index, with the reason.
/// `docs/RENDER.md` explains each entry.
const KNOWN_DIVERGENCES: &[(&str, usize, &str)] = &[];

struct Tally {
    exact: usize,
    normalized: usize,
    failures: Vec<String>,
    unexpected_passes: Vec<usize>,
}

fn check(suite: &str, cases: &[(usize, String, String)]) -> Tally {
    let mut t = Tally {
        exact: 0,
        normalized: 0,
        failures: Vec::new(),
        unexpected_passes: Vec::new(),
    };
    for (id, md, expected) in cases {
        let got = blyg_render::render_markdown(md);
        let known = KNOWN_DIVERGENCES
            .iter()
            .any(|(s, k, _)| *s == suite && k == id);
        if &got == expected {
            t.exact += 1;
        } else if std::env::var_os("BLYG_SHOW_WS").is_some() {
            eprintln!("~~~ {suite} {id}\n  expected: {expected:?}\n  got:      {got:?}");
        }
        if normalize(&got) == normalize(expected) {
            t.normalized += 1;
            if known {
                t.unexpected_passes.push(*id);
            }
        } else if !known {
            t.failures.push(format!("--- {suite} {id}\n  md:       {md:?}\n  expected: {expected:?}\n  got:      {got:?}"));
        }
    }
    eprintln!(
        "{suite} parity: {}/{} after whitespace normalisation ({} byte-identical)",
        t.normalized,
        cases.len(),
        t.exact
    );
    t
}

fn load(name: &str) -> Value {
    let path = fixtures_dir().join("parity").join(name);
    serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap()
}

fn assert_clean(t: Tally) {
    assert!(
        t.unexpected_passes.is_empty(),
        "now passing, remove from KNOWN_DIVERGENCES: {:?}",
        t.unexpected_passes
    );
    assert!(
        t.failures.is_empty(),
        "{} parity failures:\n{}",
        t.failures.len(),
        t.failures.join("\n")
    );
}

#[test]
fn commonmark_spec_parity() {
    let doc = load("_commonmark_spec.json");
    let cases: Vec<_> = doc["examples"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| {
            (
                e["example"].as_u64().unwrap() as usize,
                e["md"].as_str().unwrap().to_string(),
                e["html"].as_str().unwrap().to_string(),
            )
        })
        .collect();
    assert_eq!(cases.len(), 652);
    assert_clean(check("commonmark", &cases));
}

#[test]
fn linkify_vector_parity() {
    let doc = load("_linkify_vectors.json");
    let cases: Vec<_> = doc["cases"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
        .map(|(i, e)| {
            (
                i,
                e["md"].as_str().unwrap().to_string(),
                e["html"].as_str().unwrap().to_string(),
            )
        })
        .collect();
    assert!(cases.len() > 150);
    assert_clean(check("linkify", &cases));
}
