//! blyg-render: the studio preview pipeline (Markdown → HTML exactly as a blyg publishes it).
//!
//! A Rust port of the reference Worker's studio preview: markdown-it with
//! `html: false` + linkify + the embeds extension, TK scopes stripped and
//! tinted, and (threads only) `![[id]]` quotes resolved from the local store
//! and baked as `blockquote.blyg-transclusion` with a provenance line.
//! Parity with the Worker is tested against fixtures generated by running
//! the Worker's own TypeScript (see `tests/fixtures/gen_parity.mjs` and
//! `docs/RENDER.md`).
//!
//! ```
//! use blyg_render::{render_preview, Kind, NoResolver, RenderOpts};
//! let out = render_preview("Hello *world*", Kind::Fragment, &NoResolver, &RenderOpts::default());
//! assert_eq!(out.html, "<p data-line=\"0\">Hello <em>world</em></p>\n");
//! ```

mod embeds;
mod emph;
mod linemap;
mod linkify;
mod markdown;
mod punycode;
mod shell;
mod tk;
mod transclusion;
mod util;

pub use embeds::{embed_css, preview_script, youtube_facade_html, youtube_id};
pub use shell::{
    Attachment, Citation, ShellOpts, article_html, csp, fork_lineage_html, media_html, page_shell,
    page_shell_with, preview_media, stub_citation_html, studio_css,
};
pub use tk::{TkError, TkScope, parse_scopes};
pub use transclusion::{
    Found, NoResolver, Quote, Resolution, Resolver, Unresolved, UnresolvedReason,
};
pub use util::escape_html;

/// Crockford base32 as blyg ids use it: lowercase, no i/l/o/u.
pub const ID_ALPHABET: &str = "0123456789abcdefghjkmnpqrstvwxyz";

/// The kind of item being rendered. Only threads resolve quotes; in a
/// fragment a `![[id]]` line is literal text, as the Worker publishes it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Kind {
    Fragment,
    Thread,
}

/// The authored kind of a quoted item.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ItemKind {
    Fragment,
    Thread,
}

impl ItemKind {
    pub fn as_str(self) -> &'static str {
        match self {
            ItemKind::Fragment => "fragment",
            ItemKind::Thread => "thread",
        }
    }
}

/// Rendering options.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RenderOpts {
    /// Emit `data-line="N"` (0-based source line) on every top-level block.
    pub data_line: bool,
    /// Inject the provenance line into each quote, as the published page does.
    pub provenance: bool,
    /// The blyg's mount, prefixing provenance links to your own items
    /// (`{mount}/f/{id}/`). The Worker's default is `/blyg`; an absolute base
    /// such as `https://blyg.example.com/blyg` also works.
    pub mount: String,
    /// The thread being edited, so quoting itself is flagged as publish would.
    pub self_id: Option<String>,
}

impl Default for RenderOpts {
    fn default() -> Self {
        RenderOpts {
            data_line: true,
            provenance: true,
            mount: "/blyg".into(),
            self_id: None,
        }
    }
}

/// Counts for the status bar.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Stats {
    /// Quotes that resolved.
    pub quotes: usize,
    /// Quotes that did not, with the reason (publish would fail on these).
    pub unresolved: Vec<Unresolved>,
    /// TK scopes with output (generated spans).
    pub ai_spans: usize,
    /// TK scopes without output yet (publish would fail on these).
    pub ungenerated: usize,
    /// Malformed TK scopes (publish would fail on these).
    pub tk_errors: Vec<TkError>,
    /// YouTube facades.
    pub videos: usize,
    /// Images in the author's Markdown (not inside quoted snapshots).
    pub images: usize,
    /// The resolved quotes in directive order (the wire's `transclusions[]`).
    pub transclusions: Vec<Quote>,
}

/// A rendered preview.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Rendered {
    /// The item's content HTML (what goes inside `.item-content`).
    pub html: String,
    /// `(source_line, block_index)` for each top-level block, in document
    /// order; `block_index` counts the `[data-line]` blocks. Empty when
    /// `RenderOpts::data_line` is off.
    pub line_map: Vec<(usize, usize)>,
    pub stats: Stats,
}

/// Render a working copy as the Worker's studio preview renders it (and as
/// publish will, TK markers aside).
pub fn render_preview(
    md: &str,
    kind: Kind,
    resolver: &dyn Resolver,
    opts: &RenderOpts,
) -> Rendered {
    // Browsers hand the Worker LF-only text; normalise so line numbers agree.
    let owned;
    let md = if md.contains('\r') {
        owned = md.replace("\r\n", "\n").replace('\r', "\n");
        owned.as_str()
    } else {
        md
    };

    let (scopes, tk_errors) = tk::parse_scopes(md);
    let src = linemap::Mapped::identity(md);
    let (stripped, spans) = tk::preview_strip(&src, &scopes);
    let annotated = tk::annotate(&stripped, &spans);

    let mut stats = Stats {
        ai_spans: scopes.iter().filter(|s| s.output.is_some()).count(),
        ungenerated: scopes.iter().filter(|s| s.output.is_none()).count(),
        tk_errors,
        ..Stats::default()
    };

    // Block spans render independently (their inner blocks carry no data-line).
    let mut blocks = Vec::with_capacity(annotated.blocks.len());
    for (token, text, _line) in &annotated.blocks {
        let (html, md_stats) = markdown::render(text, None);
        stats.images += md_stats.images;
        stats.videos += md_stats.videos;
        blocks.push(tk::Block {
            token: token.clone(),
            html: format!("<div class=\"blyg-tk-gen\">{html}</div>"),
            literal: text.clone(),
        });
    }

    let doc = &annotated.doc;
    let (html, block_lines) = match kind {
        Kind::Fragment => {
            let map = |j: usize| doc.lines[j];
            let (html, md_stats) =
                markdown::render(&doc.text, if opts.data_line { Some(&map) } else { None });
            stats.images += md_stats.images;
            stats.videos += md_stats.videos;
            (html, md_stats.block_lines)
        }
        Kind::Thread => {
            let w = transclusion::walk(
                doc,
                &annotated.inert,
                resolver,
                opts.self_id.as_deref(),
                opts.data_line,
            );
            stats.images += w.md.images;
            stats.videos += w.md.videos;
            stats.quotes = w.quotes.len();
            stats.unresolved = w.unresolved;
            stats.transclusions = w.quotes.iter().map(|(q, _)| q.clone()).collect();
            let mut html = tk::apply_wrappers(w.html, &blocks, annotated.has_inline);
            if opts.provenance {
                let lines: Vec<String> = w
                    .quotes
                    .iter()
                    .map(|(_, f)| transclusion::provenance_line(f, &opts.mount))
                    .collect();
                html = transclusion::inject_provenance(&html, &lines);
            }
            let line_map = w
                .block_lines
                .into_iter()
                .enumerate()
                .map(|(i, l)| (l, i))
                .collect();
            return Rendered {
                html,
                line_map,
                stats,
            };
        }
    };
    let html = tk::apply_wrappers(html, &blocks, annotated.has_inline);
    let line_map = block_lines
        .into_iter()
        .enumerate()
        .map(|(i, l)| (l, i))
        .collect();
    Rendered {
        html,
        line_map,
        stats,
    }
}

/// Render plain Markdown exactly as the Worker's `renderMarkdown` (no TK,
/// no transclusion, no line attributes).
pub fn render_markdown(md: &str) -> String {
    markdown::render(md, None).0
}
